apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kafka-consumer-prod

namespace: kafka-consumers

resources:
  - ../../base
  - namespace.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  environment: prod

replicas:
  - name: kafka-consumer
    count: 3

images:
  - name: ghcr.io/wgu/kafka-consumer
    newTag: v1.0.0  # Pin to specific version in prod

patches:
  - path: patches/deployment-patch.yaml

configMapGenerator:
  - name: kafka-consumer-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - KAFKA_GROUP_ID=go-cdc-consumers-prod
