apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kafka-consumer-dev

namespace: kafka-consumers-dev

resources:
  - ../../base
  - namespace.yaml

commonLabels:
  environment: dev

replicas:
  - name: kafka-consumer
    count: 2

images:
  - name: ghcr.io/wgu/kafka-consumer
    newTag: latest

patches:
  - path: patches/deployment-patch.yaml

configMapGenerator:
  - name: kafka-consumer-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - KAFKA_GROUP_ID=go-cdc-consumers-dev
